trigger:
  - main

pool: 
  vmImage: 'ubuntu-24.04'

steps:
- checkout: self

- script: |
    echo Checkout completed
  
# steps:
- task: CopyFiles@1
  inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      TargetFolder: /tmp/gpr
      CleanTargetFolder: true

- script: |
     sudo apt-get update
     sudo apt-get install -y docker-ce docker-ce-cli containerd.io 
  displayName: 'Install Docker'

- script: |
      docker run --user $UID -v $(pwd):/sourceDir -v /tmp:/workingDir casthighlight/cli --sourceDir /sourceDir --workingDir /workingDir --ignoreDirectories node_modules --includeAllDependencies --applicationId 479467 --companyId 9684 --token "5b367e45-0c90-4d23-8492-296dd6812044" --serverUrl https://rpa.casthighlight.com
  displayName: 'Run Docker Highlight scan'
