parameters:
- name: clean
  displayName: Checkout clean
  type: boolean
  default: false
  values:
  - false
  - true

trigger:
- main
jobs:
- job: CP
  pool: Default
  
  steps:
  - task: CopyFiles@1
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      TargetFolder: C:\azure\agent\_src
      OverWrite: true

