parameters:
- name: clean
  displayName: Checkout clean
  type: boolean
  default: false
  values:
  - false
  - true

trigger:
- main
jobs:
- job: CO
  pool: 
    vmImage: 'windows-latest'

  steps:
  - checkout: self
    clean: ${{ parameters.clean }}

  - script: |
      echo Checkout completed
      echo    Running copy now...
    displayName: 'Run a multi-line script'
  
- job: CP
  pool: Default
  dependsOn: CO
  condition: succeeded('CO')
  
  steps:
  - task: CopyFiles@1
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      TargetFolder: C:\azure\agent\_src\shopizer
      CleanTargetFolder: true

  - task: HLScan@1
    inputs:
      filename: C:\azure\agent\_hl_scripts\HL-scan_Shopizer.bat
      #arguments: 