# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: 
  pool:
      vmImage: windows-latest
      steps:
        checkout: https://github.com/guru-CAST/shopizer
        path: \latest
  
  task: Docker@2
    inputs:
      containerRegistry: 'hl-docker'
      repository: 'https://hub.docker.com/r/casthighlight/hl-agent-cli'
      command: 'run'
      arguments: '-v $(Build.SourcesDirectory):/here -v $(Agent.TempDirectory):/there casthighlight/hl-agent-cli:5.1.9 –sourceDir here –workingDir there –skipUpload'
