parameters:
- name: clean
  displayName: Checkout clean
  type: boolean
  default: false
  values:
  - false
  - true

trigger:
- main

pool: #FabrikamPool
  vmImage: 'windows-latest'

steps:
- checkout: self
  clean: ${{ parameters.clean }}

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: CopyFiles@1
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    TargetFolder: C:\azure\agent\_src
    OverWrite: true

